//> using scala "3.7.0"
//> using jvm "17"
//> using dep "org.lz4:lz4-java:1.8.0"
//> using dep "io.get-coursier:interface:1.0.18"
//> using dep "org.scalameta:mtags-interfaces:1.5.5-SNAPSHOT,exclude=org.eclipse.lsp4j%org.eclipse.lsp4j,exclude=org.eclipse.lsp4j%org.eclipse.lsp4j.jsonrpc"
//> using dep "org.scalameta:mtags_2.13.16:1.5.5-SNAPSHOT"
//> using dep "org.eclipse.lsp4j:org.eclipse.lsp4j:0.23.1"
//> using dep "org.scala-lang:scala3-compiler_3:3.7.0"
//> using options "-source" "3.3" "-Yexplicit-nulls" "-Wsafe-init"
//> using publish.organization "org.scala-lang"
//> using publish.name "scala3-presentation-compiler"
//> using publish.version "3.7.1-SNAPSHOT"
