name: CI
on:
  push:
    branches:
    - plasmon
    tags:
    - "v*"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: coursier/cache-action@v6.4
    - uses: coursier/setup-action@v1
    - name: Test
      run: ./mill -i __.compile

  publish:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: coursier/cache-action@v6
    - uses: coursier/setup-action@v1
    - name: Publish
      run: ./mill -i mill.scalalib.SonatypeCentralPublishModule/
      env:
        MILL_PGP_SECRET_BASE64: ${{ secrets.PUBLISH_SECRET_KEY_BASE64 }}
        MILL_PGP_PASSPHRASE: ${{ secrets.PUBLISH_SECRET_KEY_PASSWORD }}
        MILL_SONATYPE_USERNAME: ${{ secrets.PUBLISH_USER }}
        MILL_SONATYPE_PASSWORD: ${{ secrets.PUBLISH_PASSWORD }}
